name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    env:
      API_KEY: '${{ secrets.SVELTE_WHEEL_API_KEY }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVELTE_WHEEL }}'
          channelId: live
          projectId: svelte-wheel
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
